# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 11:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('questionaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='docfile',
            field=models.FileField(default=datetime.datetime(2016, 5, 25, 11, 25, 3, 317619, tzinfo=utc), upload_to=b'documents'),
            preserve_default=False,
        ),
    ]
