# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionaire', '0002_question_docfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'media/documents')),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='docfile',
        ),
        migrations.AddField(
            model_name='image',
            name='Question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionaire.Question'),
        ),
    ]
