# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 06:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionaire', '0003_auto_20160525_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='Question',
            new_name='question',
        ),
    ]
