# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 06:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('questionaire', '0004_auto_20160526_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='docfile',
            field=models.FileField(default=datetime.datetime(2016, 5, 26, 6, 37, 36, 412278, tzinfo=utc), upload_to=b'media'),
            preserve_default=False,
        ),
    ]
