# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 06:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('questionaire', '0005_question_docfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='docfile',
            new_name='docfile1',
        ),
        migrations.AddField(
            model_name='question',
            name='docfile2',
            field=models.FileField(default=datetime.datetime(2016, 5, 26, 6, 41, 1, 517201, tzinfo=utc), upload_to=b'media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='docfile3',
            field=models.FileField(default=datetime.datetime(2016, 5, 26, 6, 41, 9, 293421, tzinfo=utc), upload_to=b'media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='docfile4',
            field=models.FileField(default=datetime.datetime(2016, 5, 26, 6, 41, 15, 37803, tzinfo=utc), upload_to=b'media'),
            preserve_default=False,
        ),
    ]
