# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionaire', '0006_auto_20160526_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='docfile1',
            field=models.FileField(upload_to=b'images'),
        ),
        migrations.AlterField(
            model_name='question',
            name='docfile2',
            field=models.FileField(upload_to=b'images'),
        ),
        migrations.AlterField(
            model_name='question',
            name='docfile3',
            field=models.FileField(upload_to=b'images'),
        ),
        migrations.AlterField(
            model_name='question',
            name='docfile4',
            field=models.FileField(upload_to=b'images'),
        ),
    ]
