# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 07:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('questionaire', '0007_auto_20160526_0647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='docfile1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='docfile2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='docfile3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='docfile4',
        ),
        migrations.AddField(
            model_name='choice',
            name='docfile',
            field=models.FileField(default=datetime.datetime(2016, 5, 26, 7, 9, 33, 341674, tzinfo=utc), upload_to=b'images'),
            preserve_default=False,
        ),
    ]
