# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionaire', '0008_auto_20160526_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='is_answer',
            field=models.BooleanField(default=False),
        ),
    ]
