# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionaire', '0009_choice_is_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_text', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questionaire.Level'),
            preserve_default=False,
        ),
    ]
