# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionaire', '0013_auto_20160602_0611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionaire.Student')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionaire.Level')),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='attempt',
        ),
        migrations.AddField(
            model_name='answer',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
